/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    services: Service;
    testimonials: Testimonial;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    search: Search;
    exports: Export;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'general-settings': GeneralSetting;
    'maintenance-settings': MaintenanceSetting;
    header: Header;
    footer: Footer;
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    'maintenance-settings': MaintenanceSettingsSelect<false> | MaintenanceSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: 'en' | 'zh-HK';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Shown on the page when no layout blocks are added
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-generated from the title. Edit to override.
   */
  slug: string;
  layout?:
    | (
        | {
            headline: string;
            /**
             * Shown on desktop (≥768px).
             */
            subheadline?: string | null;
            /**
             * Shown on mobile and tablet (<768px). Falls back to Subheadline if left empty.
             */
            subheadlineMobile?: string | null;
            bannerImage: number | Media;
            mobileBannerImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            /**
             * Shown on desktop (≥768px).
             */
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Shown on mobile and tablet (<768px). Falls back to Subheadline if left empty.
             */
            bodyMobile?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            animatedGif?: (number | null) | Media;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-challenge';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heart-team-coaching';
          }
        | {
            heading?: string | null;
            sectionIntro?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            values?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Optional decorative illustration shown beside this card (e.g. tree, birds, stones).
                   */
                  decorativeImage?: (number | null) | Media;
                  color?: ('teal' | 'yellow' | 'pink' | 'blue') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
        | {
            heading: string;
            subheading?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            background?: ('teal' | 'teal-gradient' | 'yellow' | 'beige') | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            services?: (number | Service)[] | null;
            /**
             * Text for the "View full services" button.
             */
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-overview';
          }
        | {
            heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            profileImage?: (number | null) | Media;
            certImages?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-me';
          }
        | {
            heading: string;
            accordionItems?:
              | {
                  title: string;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'coaching-experience';
          }
        | {
            heading: string;
            /**
             * Optional introductory paragraph shown below the heading.
             */
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            missionTitle?: string | null;
            mission?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            visionTitle?: string | null;
            vision?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-him';
          }
        | {
            /**
             * Decorative image shown alongside the shortcut text.
             */
            image?: (number | null) | Media;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-shortcut';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            services?: (number | Service)[] | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'service-detail';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            sideImage?: (number | null) | Media;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-form';
          }
        | {
            /**
             * Main heading for the section
             */
            sectionTitle: string;
            /**
             * Introductory paragraph below the heading
             */
            sectionSubtitle?: string | null;
            /**
             * List of services shown as booking cards
             */
            services?:
              | {
                  name: string;
                  description?: string | null;
                  /**
                   * e.g. https://wa.me/85212345678
                   */
                  whatsappUrl?: string | null;
                  /**
                   * Email address for booking this service. e.g. contact@heartinmotionhk.com
                   */
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control which viewports this block appears on.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnTablet?: boolean | null;
              showOnMobile?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-session';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  category: 'executive-leadership' | 'individual' | 'program-change';
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorTitle?: string | null;
  authorCompany?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All contact form submissions from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'services';
        value: number | Service;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  sort?: string | null;
  locale?: ('all' | 'en' | 'zh-HK') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              subheadlineMobile?: T;
              bannerImage?: T;
              mobileBannerImage?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'real-challenge'?:
          | T
          | {
              heading?: T;
              body?: T;
              bodyMobile?: T;
              animatedGif?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'heart-team-coaching'?:
          | T
          | {
              heading?: T;
              body?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              heading?: T;
              sectionIntro?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    decorativeImage?: T;
                    color?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              background?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-overview'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              services?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-me'?:
          | T
          | {
              heading?: T;
              body?: T;
              profileImage?: T;
              certImages?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'coaching-experience'?:
          | T
          | {
              heading?: T;
              accordionItems?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-him'?:
          | T
          | {
              heading?: T;
              body?: T;
              missionTitle?: T;
              mission?: T;
              visionTitle?: T;
              vision?: T;
              image?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-shortcut'?:
          | T
          | {
              image?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'service-detail'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              services?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-form'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              sideImage?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'booking-session'?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              services?:
                | T
                | {
                    name?: T;
                    description?: T;
                    whatsappUrl?: T;
                    email?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnTablet?: T;
                    showOnMobile?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  authorCompany?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  sort?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  /**
   * Logo displayed on the admin login page.
   */
  adminLogo?: (number | null) | Media;
  siteName?: string | null;
  siteTagline?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  bookingUrl?: string | null;
  emailMeUrl?: string | null;
  emailFromName?: string | null;
  emailFromAddress?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Control the public maintenance page shown to visitors when the site is offline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-settings".
 */
export interface MaintenanceSetting {
  id: number;
  /**
   * ⚠️ When enabled, all public visitors (without an admin session) are redirected to the maintenance page. Admins logged in can still access the site normally.
   */
  enabled?: boolean | null;
  logo?: (number | null) | Media;
  title?: string | null;
  /**
   * Optional message shown below the title. Supports rich text formatting.
   */
  message?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "Back on 1 May 2026 at 10:00 AM HKT"
   */
  estimatedReturn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        linkType?: ('page' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Two action buttons shown in the mobile menu.
   */
  mobileCta?: {
    connectLabel?: string | null;
    /**
     * e.g. booking/calendar link
     */
    connectUrl?: string | null;
    emailLabel?: string | null;
    /**
     * e.g. mailto: link
     */
    emailUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        page?: (number | null) | Page;
        /**
         * Use if linking to an external URL instead of a page
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'linkedin' | 'instagram' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  /**
   * Content shown in the Privacy Policy popup
   */
  privacyPolicy?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Content shown in the Terms & Conditions popup
   */
  termsConditions?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * When disabled, the translate button is hidden from all editors.
   */
  enabled?: boolean | null;
  /**
   * Your Claude API key (sk-ant-...). Get one at console.anthropic.com.
   */
  anthropicApiKey?: string | null;
  /**
   * Haiku is recommended for most translation tasks.
   */
  model?: ('claude-haiku-4-5-20251001' | 'claude-sonnet-4-6') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  adminLogo?: T;
  siteName?: T;
  siteTagline?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  bookingUrl?: T;
  emailMeUrl?: T;
  emailFromName?: T;
  emailFromAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-settings_select".
 */
export interface MaintenanceSettingsSelect<T extends boolean = true> {
  enabled?: T;
  logo?: T;
  title?: T;
  message?: T;
  estimatedReturn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  mobileCta?:
    | T
    | {
        connectLabel?: T;
        connectUrl?: T;
        emailLabel?: T;
        emailUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  privacyPolicy?:
    | T
    | {
        title?: T;
        content?: T;
      };
  termsConditions?:
    | T
    | {
        title?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  enabled?: T;
  anthropicApiKey?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format: 'csv' | 'json';
    limit?: number | null;
    sort?: string | null;
    locale?: ('all' | 'en' | 'zh-HK') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output: {
    success?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}